plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\applications\\telecom-support-portal\\frontend_flutter"
publishOrigin = "default"
base = "D:\\applications\\telecom-support-portal\\frontend_flutter"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]